name: C/C++ CI

on:
  push:
    branches: [ "upgrade" ]
  pull_request:
    branches: [ "upgrade" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install autotools
      run: sudo apt-get update && sudo apt-get install -y autoconf automake libtool
    - name: install external header files
      run: sudo apt install -y libperl-dev libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libfreetype-dev
    - name: generate configure script
      run: autoheader --force && automake --add-missing && autoreconf -fi
    - name: configure
      run: ./configure --enable-main --enable-characters --enable-additional --enable-thirdparty --disable-freetypetest
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
