name: C/C++ CI

on:
  push:
    branches: [ "upgrade" ]
  pull_request:
    branches: [ "upgrade" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build preparations
      run: aclocal && automake --add-missing && autoconf
    - name: configure
      run: ./configure --enable-main --enable-characters --enable-additional --enable-thirdparty -disable-freetypetest
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
