name: Build OpenMortal and create distribution packages

on:
  push:
      branches: [ upgrade ]
  pull_request:
      branches: [ upgrade ]
  workflow_dispatch:

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: install build packages and developer libraries
        run: sudo apt update && sudo apt upgrade -y &&
             sudo apt install -y build-essential autoconf automake libtool pkg-config dh-autoreconf debhelper devscripts fakeroot build-essential &&
             sudo apt install -y libperl-dev libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libfreetype6-dev
      - name: autoreconf
        run: autoreconf -i
      - name: configure
        run: ./configure
      - name: make
        run: make
      - name: build compressed packages
        run: make dist
