name: OpenMortal multi-platform build & release

on:
  push:
    branches: [ upgrade ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ upgrade ]
  workflow_dispatch:

env:
  APPIMAGE_EXTRACT_AND_RUN: 1
  VERSION: 0.7.2
  DIST_FOLDER: ../distribution/
jobs:
  linux-x86-64_build:
    runs-on: ubuntu-latest
    env:
      OSNAME: linux-ubuntu-noble
      PLATFORM: x86-64
    container:
      image: ubuntu:24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt update && apt upgrade -y &&
          apt-get install -y wget
          apt install -y build-essential autoconf automake libtool pkg-config dh-autoreconf debhelper devscripts fakeroot build-essential &&
          apt install -y libperl-dev libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libfreetype6-dev

      - name: Build from source
        run: |
          autoreconf -i -f
          ./configure --prefix=/usr
          make -j$(nproc)

      - name: Create distributable archive
        run: |
          make dist

      - name: make binary files
        run: |
          make DESTDIR=$DIST_FOLDER/linux-$PLATFORM_build/usr install
          ls -lR $DIST_FOLDER/linux-$PLATFORM_build/usr

      - name: Prepare AppImage environment
        run: |
          ls -lR $DIST_FOLDER/linux-$PLATFORM_build/usr
          mkdir -p $DIST_FOLDER/AppDir/usr/bin
          install -m755 ./src/openmortal $DIST_FOLDER/AppDir/usr/bin/openmortal
          mkdir -p $DIST_FOLDER/AppDir/usr/share/icons/hicolor/32x32/apps
          install -m644 $DIST_FOLDER/linux-$PLATFORM_build/usr/share/openmortal/data/gfx/icon.png $DIST_FOLDER/AppDir/usr/share/icons/hicolor/32x32/apps/openmortal.png
          mkdir -p $DIST_FOLDER/AppDir/usr/share/openmortal
          cp -a data $DIST_FOLDER/AppDir/usr/share/openmortal
          install -m644 packaging/openmortal.AppImage.desktop $DIST_FOLDER/AppDir/openmortal.desktop
          mkdir -p $DIST_FOLDER/linux-$PLATFORM-package/usr/bin
          install -m755 ./src/openmortal $DIST_FOLDER/linux-$PLATFORM-package/usr/bin/openmortal
          mkdir -p $DIST_FOLDER/linux-$PLATFORM-package/usr/share/openmortal
          cp -a $DIST_FOLDER/linux-$PLATFORM_build/usr/openmortal/ $DIST_FOLDER/linux-$PLATFORM-package/usr/share/openmortal/
          tar zcvf -C $DIST_FOLDER/linux-$PLATFORM-package/ openmortal-$VERSION_linux_$PLATFORM.tar.gz .

      - name: Download linuxdeploy and appimagetool
        run: |
          wget -qO /tmp/linuxdeploy-x86_64.AppImage "https:/github.com/linuxdeploy/linuxdeploy/releases/latest/download/linuxdeploy-x86_64.AppImage"
          chmod +x /tmp/linuxdeploy-x86_64.AppImage
          wget -qO /tmp/appimagetool.AppImage "https:/github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage"
          chmod +x /tmp/appimagetool.AppImage

      - name: Create AppImage
        run: |
          /tmp/linuxdeploy-x86_64.AppImage --appdir $DIST_FOLDER/AppDir --desktop-file=$DIST_FOLDER/AppDir/openmortal.desktop --icon-file=$DIST_FOLDER/AppDir/usr/share/icons/hicolor/32x32/apps/openmortal.png
          /tmp/appimagetool.AppImage $DIST_FOLDER/AppDir

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: openmortal_appimage_$PLATFORM
          path: ../*.AppImage
      #- name: Upload Linux source xz archives for $PLATFORM/
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: openmortal_linux_binary_$PLATFORM/.xz
      #    path: ../openmortal-0.7.tar.xz
      - name: Upload Linux source gzip archives for $PLATFORM/
        uses: actions/upload-artifact@v4
        with:
          name: openmortal_linux_binary_$PLATFORM.gz
          path: ./openmortal-?.?.tar.gz
      - name: Upload Linux binary gzip archives for $PLATFORM/
        uses: actions/upload-artifact@v4
        with:
          name: openmortal_linux_binary_$PLATFORM.gz
          path: openmortal-*_linux_$PLATFORM.tar.gz
