name: OpenMortal multi-platform build & release

on:
  push:
    branches: [ upgrade ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ upgrade ]
  workflow_dispatch:

env:
  APPIMAGE_EXTRACT_AND_RUN: 1

jobs:
  appimage:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt update && apt upgrade -y &&
          apt-get install -y wget
          apt install -y build-essential autoconf automake libtool pkg-config dh-autoreconf debhelper devscripts fakeroot build-essential &&
          apt install -y libperl-dev libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libfreetype6-dev

      - name: Build from source
        run: |
          autoreconf -i -f
          ./configure --prefix=/usr
          make -j$(nproc)

      - name: Create distibuteble archive
        run: |
          make dist dist-xz
          make DESTDIR=../openmortal-0.7_linux_x86-64 install
          tar zcvf -C ../openmortal-0.7_linux_x86-64 openmortal-0.7_linux_x86-64.tar.gz

      - name: Prepare AppImage environment
        run: |
          make DESTDIR=../AppDir install
          #mkdir -p ../AppDir/usr/bin
          #install -m755 src/openmortal ../AppDir/usr/bin/openmortal
          mkdir -p ../AppDir/usr/share/icons/hicolor/32x32/apps
          install -m644 data/gfx/icon.png ../AppDir/usr/share/icons/hicolor/32x32/apps/openmortal.png
          #mkdir -p ../AppDir/usr/share/openmortal
          #cp -a data ../AppDir/usr/share/openmortal
          install -m644 packaging/openmortal.AppImage.desktop ../AppDir/openmortal.desktop

      - name: Download linuxdeploy and appimagetool
        run: |
          wget -qO /tmp/linuxdeploy-x86_64.AppImage "https://github.com/linuxdeploy/linuxdeploy/releases/latest/download/linuxdeploy-x86_64.AppImage"
          chmod +x /tmp/linuxdeploy-x86_64.AppImage
          wget -qO /tmp/appimagetool.AppImage "https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage"
          chmod +x /tmp/appimagetool.AppImage

      - name: Create AppImage
        run: |
          /tmp/linuxdeploy-x86_64.AppImage --appdir ../AppDir --desktop-file=../AppDir/openmortal.desktop --icon-file=../AppDir/usr/share/icons/hicolor/32x32/apps/openmortal.png
          /tmp/appimagetool.AppImage ../AppDir

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: openmortal_appimage_x86-64
          path: ../*.AppImage
      - name: Upload Linux source xz archives for x86-64
        uses: actions/upload-artifact@v4
        with:
          name: openmortal_linux_binary_x86-64.xz
          path: ../openmortal-0.7.tar.xz
      - name: Upload Linux source gzip archives for x86-64
        uses: actions/upload-artifact@v4
        with:
          name: openmortal_linux_binary_x86-64.gz
          path: ./openmortal-?.?.tar.gz
      - name: Upload Linux binary gzip archives for x86-64
        uses: actions/upload-artifact@v4
        with:
          name: openmortal_linux_binary_x86-64.gz
          path: openmortal-*_linux_x86-64.tar.gz
